### ISSUE TITLE
LaTeX error message

### ISSUE THREAD

**Issue by khinsen** [nuest/reproducible-research-and-giscience#3]
Using Binder, and following the instructions step by step (after applying #2), I end up getting the following LaTeX error that prevents the generation of the PDF:
```
! LaTeX Error: File `tabu.sty' not found.
```

**Comment by nuest** [comment]
_Thanks for reporting!_ I can confirm errors with the PDF generation both locally and on mybinder.org, although `tabo.sty` is not the one I get:

https://github.com/yihui/tinytex/issues/47

Will updates this issue once the problems are resolved.

**Comment by nuest** [comment]
The full process now works again:

[![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/nuest/reproducible-research-and-giscience/5)

or 

https://mybinder.org/v2/gh/nuest/reproducible-research-and-giscience/5

Some minor changes were made to the documentation and different defaults for example data (more data):

![image](https://user-images.githubusercontent.com/1325054/40433051-600ab73a-5eab-11e8-869b-77a141eb5e72.png)

![image](https://user-images.githubusercontent.com/1325054/40433179-aa656b18-5eab-11e8-8033-d3ce9285ea2a.png)


(Let me know if you're interested in taking a go at the original data, I will send you a link.)
