### ISSUE TITLE
R library missing in Docker image

### ISSUE THREAD

**Issue by khinsen** [nuest/reproducible-research-and-giscience#4]
I built and ran the Docker image on my own computer, then started the RStudio session and did Knit->PDF. R stops with an error on line 36, saying there is no package called "gridBase". Unfortunately I cannot copy-paste the full message from the RStudio Web app.

**Comment by nuest** [comment]
I can confirm your error. I failed to make sure that, after making "merely" "editorial" changes, the binder still works.
